"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'vi' | 'en' | 'zh';

interface Translations {
  [key: string]: {
    [key in Language]: string;
  };
}

export const TRANSLATIONS: Translations = {
  // Navigation & Common
  clear: { vi: 'Xóa nội dung', en: 'Clear search', zh: '清除搜索' },
  back_to_dashboard: { vi: 'Quay lại Dashboard', en: 'Back to Dashboard', zh: '返回仪表板' },
  all: { vi: 'Tất cả', en: 'All', zh: '全部' },
  select_all: { vi: 'Chọn tất cả', en: 'Select All', zh: '全选' },
  in: { vi: 'VÀO', en: 'IN', zh: '进入' },
  out: { vi: 'RA', en: 'OUT', zh: '退出' },
  search: { vi: 'Tìm kiếm', en: 'Search', zh: '搜索' },
  reset: { vi: 'Đặt lại', en: 'Reset', zh: '重置' },
  apply: { vi: 'Áp dụng', en: 'Apply', zh: '应用' },
  load_more: { vi: 'Xem thêm', en: 'Load More', zh: '加载更多' },
  no_logs_found: { vi: 'Không tìm thấy nhật ký nào khớp bộ lọc', en: 'No logs found matching your filters', zh: '未找到符合筛选条件的日志' },
  status: { vi: 'Tình trạng', en: 'Status', zh: '状态' },
  created_at: { vi: 'Ngày tạo', en: 'Created At', zh: '创建时间' },
  confirm: { vi: 'Xác nhận', en: 'Confirm', zh: '确认' },
  retry: { vi: 'Thử lại', en: 'Retry', zh: '重试' },
  loading: { vi: 'Đang tải...', en: 'Loading...', zh: '正在加载...' },
  loading_data: { vi: 'Đang tải dữ liệu...', en: 'Loading data...', zh: '正在加载数据...' },
  close: { vi: 'Đóng', en: 'Close', zh: '关闭' },
  cancel: { vi: 'Hủy', en: 'Cancel', zh: '取消' },
  save: { vi: 'Lưu thay đổi', en: 'Save Changes', zh: '保存更改' },
  search_placeholder: { vi: 'Tìm theo mã NV, Tên...', en: 'Search by EmpNo, Name...', zh: '按工号，姓名搜索...' },
  user_config: { vi: 'Cấu hình người dùng', en: 'User Config', zh: '用户配置' },
  device_manager: { vi: 'Quản lý thiết bị', en: 'Device Manager', zh: '设备管理' },
  dashboard: { vi: 'Bảng điều khiển', en: 'Dashboard', zh: '仪表板' },
  fac_facial_access_control: { vi: 'AW-GGP', en: 'AW-GGP', zh: 'AW-GGP' },
  exception_report: { vi: 'Giải trình sự cố', en: 'Exception Report', zh: '异常报告' },
  col_handler_group: { vi: 'Thông tin người xử lý', en: 'Handler Information', zh: '经办人信息' },
  col_employee_group: { vi: 'Thông tin nhân viên', en: 'Employee Information', zh: '员工信息' },
  col_fullname: { vi: 'Họ tên', en: 'Full Name', zh: '姓名' },
  col_explanation_file: { vi: 'Đính kèm file bao gồm: Truy cập quá hạn, người lạ truy cập (trong và ngoài giờ làm việc),....', en: 'Attach file (incl. expired access, unauthorized access inside/outside working hours),...', zh: '附件（包括：过期访问、陌生人入侵（工作时间内外）等）,...' },
  col_explanation_reason: { vi: 'Lý do', en: 'Reason', zh: '原因' },
  col_corrective_action: { vi: 'Hành động khắc phục phòng ngừa', en: 'Corrective & Preventive Action', zh: '纠正与预防措施' },
  col_handler_info: { vi: 'Người xử lý', en: 'Handler Info', zh: '经办人' },
  col_security_confirm: { vi: 'BV xác nhận', en: 'SG Conf.', zh: '保安确认' },
  col_ps_confirm: { vi: 'ANSP xác nhận', en: 'PS Confirm', zh: '空港保安确认' },
  col_explanation_remark: { vi: 'Ghi chú', en: 'Remark', zh: '备注' },
  col_action: { vi: 'Thao tác', en: 'Action', zh: '操作' },
  btn_submit_explanation: { vi: 'Xác nhận giải trình', en: 'Submit Explanation', zh: '确认说明' },
  upload_file_hint: { vi: 'Nhấp để chọn file (word/excel...)', en: 'Click to select file (word/excel...)', zh: '点击选择文件 (word/excel...)' },
  success_submit_explanation: { vi: 'Giải trình đã được lưu thành công!', en: 'Explanation saved successfully!', zh: '说明已成功保存！' },
  explanation_modal_title: { vi: 'Cập nhật Giải Trình Sự Cố', en: 'Update Incident Explanation', zh: '更新事故说明' },
  filter_all: { vi: 'Tất cả', en: 'All', zh: '全部' },
  filter_confirmed: { vi: 'Đã xác nhận', en: 'Confirmed', zh: '已确认' },
  filter_unconfirmed: { vi: 'Chưa xác nhận', en: 'Unconfirmed', zh: '未确认' },
  clear_filter: { vi: 'Xóa lọc', en: 'Clear Filter', zh: '清除筛选' },
  filter_search_quick: { vi: 'Tìm nhanh...', en: 'Quick search...', zh: '快速搜索...' },
  filter_search_emp: { vi: 'Tìm theo tên, mã thẻ...', en: 'Search by name, ID...', zh: '按姓名、工号搜索...' },
  status_pending: { vi: 'Chưa xử lý', en: 'Pending', zh: '未处理' },
  status_processed: { vi: 'Đã xử lý', en: 'Processed', zh: '已处理' },
  placeholder_reason: { vi: 'Vui lòng nhập lý do giải trình chi tiết...', en: 'Please enter detailed explanation reason...', zh: '请输入详细的说明原因...' },
  placeholder_action: { vi: 'Vui lòng nhập hành động khắc phục và phòng ngừa...', en: 'Please enter corrective and preventive action...', zh: '请输入纠正与预防措施...' },
  placeholder_remark: { vi: 'Nhập ghi chú thêm nếu có...', en: 'Enter additional remark if any...', zh: '如有，请输入附加备注...' },
  remark_modal_title: { vi: 'Chi tiết ghi chú', en: 'Remark Details', zh: '备注详情' },

  // Dashboard Specific
  live_status: { vi: 'TRỰC TIẾP', en: 'LIVE', zh: '直播' },
  section_area_status: { vi: 'Trạng thái khu vực', en: 'Area Status', zh: '区域状态' },
  section_access_log: { vi: 'Nhật ký ra vào', en: 'Access Log', zh: '访问日志' },
  stats_inside: { vi: 'Bên Trong', en: 'Inside Building', zh: '大楼内' },
  stats_entries: { vi: 'Lượt vào', en: 'Entries', zh: '今日进入' },
  stats_denied: { vi: 'Từ chối', en: 'Denied', zh: '今日拒绝' },
  stats_online: { vi: 'Thiết bị Online', en: 'Devices Online', zh: '在线设备' },
  search_user_hint: { vi: 'Tìm theo tên, mã NV, bộ phận, khu vực...', en: 'Search name, ID, Dept, Area...', zh: '搜索姓名、工号、部门、区域...' },
  filter_by_time: { vi: 'Lọc theo thời gian', en: 'Filter by Time', zh: '按时间过滤' },
  from: { vi: 'Từ', en: 'From', zh: '从' },
  to: { vi: 'Đến', en: 'To', zh: '至' },
  
  // Charts
  traffic_trend: { vi: 'Lưu lượng trong ngày', en: 'Traffic Trend', zh: '今日流量' },
  traffic_trend_desc: { vi: 'Số lượt ra/vào theo từng giờ', en: 'IN/OUT flow per hour', zh: '每小时进出次数' },
  auth_results: { vi: 'Kết quả nhận diện', en: 'Authentication Results', zh: '认证结果' },
  auth_results_desc: { vi: 'Tỷ lệ Thành công / Từ chối', en: 'Success vs Denied ratio', zh: '成功与拒绝比例' },
  status_success: { vi: 'Thành công', en: 'Success', zh: '成功' },
  status_denied: { vi: 'Từ chối', en: 'Denied', zh: '拒绝' },
  total: { vi: 'Tổng', en: 'Total', zh: '总额' },
  show_charts: { vi: 'Hiện biểu đồ', en: 'Show Charts', zh: '显示图表' },
  hide_charts: { vi: 'Ẩn biểu đồ', en: 'Hide Charts', zh: '隐藏图表' },

  // System Notifications
  report: { vi: 'Báo cáo', en: 'Report', zh: '报告' },
  expand: { vi: 'Mở rộng', en: 'Expand', zh: '展开' },
  collapse: { vi: 'Thu gọn', en: 'Collapse', zh: '折叠' },
  success: { vi: 'Thành công', en: 'Success', zh: '已通过' },
  denied: { vi: 'Từ chối', en: 'Denied', zh: '已拒绝' },

  // Device Manager Specific
  device_mgr_subtitle: { vi: 'Quản lý trạng thái và cấu hình thiết bị nhận diện', en: 'Manage status and configuration of recognition devices', zh: '管理识别设备的状态和配置' },
  realtime_ping: { vi: 'Đã tích hợp Ping Real-time', en: 'Real-time Ping Integrated', zh: '已集成实时 Ping' },
  total_devices: { vi: 'Tổng số thiết bị', en: 'Total Devices', zh: '设备总数' },
  total_areas: { vi: 'Khu vực kiểm soát', en: 'Controlled Areas', zh: '受控区域' },
  online_status: { vi: 'Đang Online', en: 'Online', zh: '在线' },
  offline_status: { vi: 'Mất kết nối', en: 'Offline', zh: '离线' },
  all_online: { vi: 'Tất cả online', en: 'All online', zh: '全部在线' },
  all_offline: { vi: 'Tất cả offline', en: 'All offline', zh: '全部离线' },
  some_offline: { vi: 'Có thiết bị offline', en: 'Some devices offline', zh: '部分设备离线' },
  managing: { vi: 'Đang quản lý', en: 'Managing', zh: '正在管理' },
  active_stable: { vi: 'Hoạt động ổn định', en: 'Working Stable', zh: '运行稳定' },
  need_check: { vi: 'Cần kiểm tra', en: 'Need Check', zh: '需要检查' },
  already_setup: { vi: 'Đã thiết lập', en: 'Already Setup', zh: '已设置' },
  all_devices: { vi: 'Tất cả thiết bị', en: 'All Devices', zh: '所有设备' },
  all_areas: { vi: 'Tất cả khu vực', en: 'All Areas', zh: '所有区域' },
  system_wide: { vi: 'Toàn hệ thống', en: 'System Wide', zh: '全系统' },
  add_device: { vi: 'Thêm thiết bị', en: 'Add Device', zh: '添加设备' },
  edit_device: { vi: 'Sửa thiết bị', en: 'Edit Device', zh: '编辑设备' },
  device_name: { vi: 'Tên thiết bị', en: 'Device Name', zh: '设备名称' },
  ip_address: { vi: 'Địa chỉ IP', en: 'IP Address', zh: 'IP地址' },
  door_location: { vi: 'Vị trí cửa', en: 'Door Location', zh: '门位置' },
  direction_in_out: { vi: 'Hướng ra vào', en: 'Direction', zh: '出入方向' },
  device_status: { vi: 'Trạng thái thiết bị', en: 'Device Status', zh: '设备状态' },
  add_area: { vi: 'Thêm khu vực', en: 'Add Area', zh: '添加区域' },
  add_area_new: { vi: 'Thêm Khu vực mới', en: 'Add New Area', zh: '添加新区域' },
  edit_area: { vi: 'Sửa khu vực', en: 'Edit Area', zh: '编辑区域' },
  area_config: { vi: 'Cấu hình Khu vực', en: 'Area Configuration', zh: '区域配置' },
  area_name: { vi: 'Tên khu vực', en: 'Area Name', zh: '区域名称' },
  area_code: { vi: 'Mã khu vực', en: 'Area Code', zh: '区域代码' },
  area_locked: { vi: 'Khóa khu vực', en: 'Area Locked', zh: '区域已锁定' },
  type_free: { vi: 'Tự do', en: 'Free Access', zh: '自由进出' },
  type_internal: { vi: 'Nội bộ', en: 'Internal Only', zh: '仅内部' },
  type_restricted: { vi: 'KV cấm', en: 'Restricted', zh: '禁区' },
  access_permission: { vi: 'Quyền ra vào', en: 'Access Permission', zh: '访问权限' },
  working_status: { vi: 'Trạng thái làm việc', en: 'Working Status', zh: '工作状态' },
  in_use: { vi: 'Đang sử dụng', en: 'In Use', zh: '使用中' },
  time_start: { vi: 'Giờ bắt đầu', en: 'Start Time', zh: '开始时间' },
  time_end: { vi: 'Giờ kết thúc', en: 'End Time', zh: '结束时间' },
  entries_exits: { vi: 'Lượt ra vào', en: 'Entries/Exits', zh: '出入次数' },
  confirm_delete_device: { vi: 'Bạn có chắc chắn muốn gỡ thiết bị này?', en: 'Are you sure you want to remove this device?', zh: '您确定要移除此设备吗？' },
  err_load_config: { vi: 'Không thể tải cấu hình dữ liệu.', en: 'Failed to load configuration data.', zh: '无法加载配置数据。' },
  syncing_hrm: { vi: 'Đang đồng bộ dữ liệu từ HRM...', en: 'Syncing data from HRM...', zh: '正在从 HRM 同步数据...' },
  sync_success: { vi: 'Đồng bộ thành công!', en: 'Sync successful!', zh: '同步成功！' },
  sync_added: { vi: 'Thêm: {count}', en: 'Added: {count}', zh: '添加：{count}' },
  sync_updated: { vi: 'Cập nhật: {count}', en: 'Updated: {count}', zh: '更新：{count}' },
  sync_locked: { vi: 'Đã khóa: {count}', en: 'Locked: {count}', zh: '锁定：{count}' },
  sync_failed: { vi: 'Lỗi đồng bộ', en: 'Sync failed', zh: '同步失败' },
  conn_failed: { vi: 'Lỗi kết nối', en: 'Connection error', zh: '连接错误' },
  conn_server_failed: { vi: 'Không thể kết nối đến máy chủ API.', en: 'Could not connect to API server.', zh: '无法连接到 API 服务器。' },
  
  // Email Report Config
  email_config: { vi: 'Cấu hình Email', en: 'Email Config', zh: '邮件配置' },
  email_config_title: { vi: 'Cấu hình Email Báo Cáo', en: 'Email Report Config', zh: '邮件报告配置' },
  email_recipient_label: { vi: 'Người nhận báo cáo (17:00)', en: 'Report Recipients (17:00)', zh: '报告接收者 (17:00)' },
  email_hint: { vi: 'Hệ thống tự động tách email theo dòng kẻ hoặc dấu phẩy.', en: 'System splits emails by lines or commas.', zh: '系统按行或逗号拆分邮件。' },
  btn_test_email: { vi: 'Test Gửi Email', en: 'Test Email', zh: '测试邮件' },
  btn_save_config: { vi: 'Lưu cấu hình', en: 'Save Config', zh: '保存配置' },
  report_enabled: { vi: 'Đang báo cáo lúc 17h - Nhấn để tắt', en: 'Reporting at 17:00 - Click to disable', zh: '17:00 报告中 - 点击禁用' },
  report_disabled: { vi: 'Bật báo cáo 17h', en: 'Enable 17:00 reporting', zh: '启用 17:00 报告' },
  report_success_msg: { vi: 'Đã lưu cấu hình thành công!', en: 'Configuration saved successfully!', zh: '配置保存成功！' },
  report_error_msg: { vi: 'Lỗi khi lưu dữ liệu', en: 'Error saving data', zh: '保存数据时出错' },
  report_test_result: { vi: 'Kết quả: ', en: 'Result: ', zh: '结果：' },
  report_test_request: { vi: 'Đã gửi yêu cầu', en: 'Request sent', zh: '请求已发送' },
  report_conn_error: { vi: 'Lỗi kết nối API', en: 'API connection error', zh: 'API 连接错误' },

  // User Config Specific
  user_mgmt_subtitle: { vi: 'Quản lý quyền hạn và trạng thái nhân viên toàn hệ thống', en: 'Manage permissions and employee status system-wide', zh: '全系统管理权限和员工状态' },
  sync_hrm: { vi: 'Đồng bộ HRM', en: 'Sync HRM', zh: '同步 HRM' },
  bulk_perm: { vi: 'Cấp quyền Bộ phận', en: 'Bulk Dept Perm', zh: '部门批量授权' },
  dept: { vi: 'Bộ phận', en: 'Department', zh: '部门' },
  filter_dept: { vi: 'Lọc theo bộ phận', en: 'Filter by Department', zh: '按部门筛选' },
  stats_total_users: { vi: 'Tổng nhân viên', en: 'Total Users', zh: '员工总数' },
  stats_active_users: { vi: 'Đang làm việc', en: 'Active Users', zh: '在职员工' },
  stats_locked_users: { vi: 'Tài khoản khóa', en: 'Locked Users', zh: '锁定账户' },
  resigned: { vi: 'Nghỉ việc', en: 'Resigned', zh: '离职' },
  resigned_sub: { vi: 'NV đã nghỉ việc', en: 'Resigned employees', zh: '离职员工' },
  status_active: { vi: 'Đang hoạt động', en: 'Active', zh: '有效' },
  status_locked: { vi: 'Bị khóa', en: 'Locked', zh: '锁定' },
  status_resigned: { vi: 'Đã nghỉ việc', en: 'Resigned', zh: '离职' },
  select_user_hint: { vi: 'Chọn nhân viên để xem chi tiết', en: 'Select an employee to view details', zh: '选择员工以查看详情' },
  emp_id: { vi: 'Mã NV', en: 'Empno', zh: '员工号' },
  note: { vi: 'Ghi chú', en: 'Note', zh: '备注' },
  lock_account: { vi: 'Khóa TK', en: 'Lock Account', zh: '锁定账户' },
  unlock_account: { vi: 'Mở khóa', en: 'Unlock Account', zh: '解锁账户' },
  perm_matrix_title: { vi: 'Quyền truy cập khu vực', en: 'Area Access Matrix', zh: '区域访问矩阵' },
  grant_perm: { vi: 'Cấp quyền', en: 'Grant Permission', zh: '授予权限' },
  expiry_date: { vi: 'Hạn dùng', en: 'Expiry Date', zh: '有效期' },
  permanent: { vi: 'Vĩnh viễn', en: 'Permanent', zh: '永久' },
  revoked: { vi: 'Đã thu hồi', en: 'Revoked', zh: '已撤销' },
  active_status: { vi: 'Hiệu lực', en: 'Active', zh: '有效' },
  view_history_hint: { vi: 'Xem lịch sử thay đổi', en: 'View change history', zh: '查看变更历史' },
  history_title: { vi: 'Lịch sử thay đổi quyền', en: 'Permission History', zh: '权限变更历史' },
  history_empty: { vi: 'Chưa có lịch sử thay đổi cho khu vực này.', en: 'No history found for this area.', zh: '该区域尚无变更历史。' },
  history_time: { vi: 'Thời gian', en: 'Time', zh: '时间' },
  history_action: { vi: 'Hành động', en: 'Action', zh: '操作' },
  history_reason: { vi: 'Lý do', en: 'Reason', zh: '原因' },
  history_performer: { vi: 'Người thực hiện', en: 'Performed By', zh: '执行者' },
  history_action_grant: { vi: 'CẤP QUYỀN', en: 'GRANT', zh: '授权' },
  history_action_revoke: { vi: 'THU HỒI', en: 'REVOKE', zh: '撤销' },
  grant_access_confirm: { vi: 'Cấp quyền', en: 'Grant Access', zh: '授权' },
  grant_access_title: { vi: 'Cấp quyền truy cập', en: 'Grant Access Permission', zh: '授予访问权限' },
  select_area_hint: { vi: 'Chọn khu vực...', en: 'Select area...', zh: '选择区域...' },
  expiry_permanent_hint: { vi: 'Hạn sử dụng (bỏ trống = vĩnh viễn)', en: 'Expiry date (leave blank for permanent)', zh: '有效期（留空则为永久）' },
  lock_reason_prefix: { vi: 'Lý do', en: 'Reason for', zh: '原因' },
  lock_modal_title_lock: { vi: 'Khóa tài khoản', en: 'Lock Account', zh: '锁定账号' },
  lock_modal_title_unlock: { vi: 'Mở khóa tài khoản', en: 'Unlock Account', zh: '解锁账号' },
  lock_modal_desc_lock: { vi: 'Bạn đang khóa tài khoản của "{name}". Nhân viên sẽ bị từ chối truy cập đến khi được mở khóa.', en: 'You are locking the account of "{name}". The employee will be denied access until unlocked.', zh: '您正在锁定 “{name}” 的账号。该员工将被拒绝访问，直到解锁。' },
  lock_modal_desc_unlock: { vi: 'Mở khóa tài khoản cho "{name}" và cho phép truy cập trở lại.', en: 'Unlock account for "{name}" and restore access.', zh: '解锁 “{name}” 的账号并恢复访问权限。' },
  lock_confirm_btn: { vi: 'Xác nhận khóa', en: 'Confirm Lock', zh: '确认锁定' },
  unlock_confirm_btn: { vi: 'Mở khóa', en: 'Unlock Account', zh: '开启访问' },
  reason_placeholder: { vi: 'Nhập lý do chi tiết...', en: 'Enter detailed reason...', zh: '输入详细原因...' },
  area_time_start_hint: { vi: 'Giờ bắt đầu của khu vực', en: 'Area start time', zh: '区域开始时间' },
  area_time_end_hint: { vi: 'Giờ kết thúc của khu vực', en: 'Area end time', zh: '区域结束时间' },
  perm_grant_success: { vi: 'Cấp quyền thành công', en: 'Permission granted successfully', zh: '授权成功' },
  perm_update_success: { vi: 'Cập nhật quyền thành công', en: 'Permission updated successfully', zh: '权限更新成功' },
  perm_revoke_success: { vi: 'Thu hồi quyền thành công', en: 'Permission revoked successfully', zh: '撤销权限成功' },
  expiry_update_success: { vi: 'Cập nhật hạn dùng thành công', en: 'Expiry date updated successfully', zh: '有效期更新成功' },
  time_update_success: { vi: 'Cập nhật khung giờ thành công', en: 'Time range updated successfully', zh: '时间段更新成功' },
  reason_required: { vi: 'Vui lòng nhập lý do', en: 'Please enter a reason', zh: '请输入原因' },
  history_load_failed: { vi: 'Lỗi tải lịch sử', en: 'Failed to load history', zh: '加载历史记录失败' },
  bulk_selection_required: { vi: 'Vui lòng chọn ít nhất một bộ phận và một khu vực', en: 'Please select at least one department and one area', zh: '请至少选择一个部门和一个区域' },
  individual_time_hint: { vi: 'Giờ riêng: {time} (Khu vực: {areaTime})', en: 'Individual time: {time} (Area: {areaTime})', zh: '个人时间：{time}（区域：{areaTime}）' },
  default_time_hint: { vi: 'Theo khu vực: {time}', en: 'Default for area: {time}', zh: '按区域：{time}' },
  unauthorized_desc_config: { vi: 'Bạn không có quyền thay đổi cấu hình người dùng. Vui lòng liên hệ Admin.', en: 'You do not have permission to change user configuration. Please contact Admin.', zh: '您没有更改用户配置的权限。请联系管理员。' },

  // Bulk Permission Modal
  bulk_modal_title: { vi: 'Cấp quyền theo Bộ phận', en: 'Bulk Dept Permission', zh: '按部门批量授权' },
  bulk_dept_label: { vi: 'Bộ phận', en: 'Department', zh: '部门' },
  bulk_dept_hint: { vi: 'Gõ để tìm bộ phận...', en: 'Type to search dept...', zh: '输入以搜索部门...' },
  bulk_areas_label: { vi: 'Khu vực áp dụng', en: 'Applicable Areas', zh: '适用区域' },
  bulk_overwrite_label: { vi: 'Ghi đè quyền đã có sẵn', en: 'Overwrite existing permissions', zh: '覆盖现有权限' },
  bulk_preview_label: { vi: 'Nhân viên sẽ được cấp', en: 'Users to be granted', zh: '将授予权限的员工' },
  bulk_select_dept_hint: { vi: 'Chọn bộ phận để xem danh sách', en: 'Select department to view list', zh: '选择部门以查看列表' },
  bulk_no_active_users: { vi: 'Không có nhân viên active', en: 'No active users found', zh: '未找到在职员工' },
  bulk_apply_btn: { vi: 'Áp dụng cho {count} nhân viên', en: 'Apply to {count} users', zh: '应用于 {count} 名员工' },
  deselect_all: { vi: 'Bỏ chọn tất cả', en: 'Deselect All', zh: '取消全选' },
  selected_count: { vi: '{count} bộ phận được chọn', en: '{count} depts selected', zh: '已选 {count} 个部门' },

  // Table Columns
  col_image: { vi: 'Ảnh', en: 'Image', zh: '图片' },
  col_time: { vi: 'Thời gian', en: 'Time', zh: '时间' },
  col_employee: { vi: 'Nhân viên', en: 'Name', zh: '员工' },
  col_dept: { vi: 'Bộ phận', en: 'Dept', zh: '部门' },
  col_area: { vi: 'Khu vực', en: 'Area', zh: '区域' },
  col_device: { vi: 'Thiết bị', en: 'Device', zh: '设备' },
  col_dir: { vi: 'Cổng', en: 'Gate', zh: '门' },
  col_in: { vi: 'VÀO', en: 'IN', zh: '进入' },
  col_out: { vi: 'RA', en: 'OUT', zh: '退出' },
  col_match: { vi: 'Độ khớp', en: 'Match', zh: '相似度' },
  col_result: { vi: 'Kết quả', en: 'Result', zh: '结果' },
  col_gate: { vi: 'Cổng', en: 'Gate', zh: '门' },
  auto_expire_limit: { vi: '* Thời hạn tự động (Tối đa 3 tháng)', en: '* Auto expiration (Max 3 months)', zh: '* 自动到期 (最多 3 个月)' },
  renewed_by: { vi: 'Đã gia hạn bởi', en: 'Renewed by', zh: '已延长' },
  conflict_perm_detected: { vi: 'Phát hiện nhân sự đã có quyền truy cập. Vui lòng chọn người khác hoặc thay đổi khu vực!', en: 'Active permissions detected for some personnel. Please choose other personnel or change areas!', zh: '检测到部分人员已拥有有效权限。请选择其他人员或更改区域！' },

  // Deny Reasons (Detailed)
  reason_unknown: { vi: 'Không nhận diện được', en: 'Unknown Face', zh: '未知面孔' },
  reason_locked: { vi: 'Tài khoản bị khóa', en: 'Account Locked', zh: '账户已锁定' },
  reason_resigned: { vi: 'Đã nghỉ việc', en: 'Resigned', zh: '已离职' },
  reason_time: { vi: 'Ngoài giờ cho phép', en: 'Out of Time', zh: '超时' },
  reason_no_perm: { vi: 'Không có quyền', en: 'No Permission', zh: '没有权限' },
  reason_expired: { vi: 'Quyền hết hạn', en: 'Expired', zh: '已过期' },
  reason_revoked: { vi: 'Quyền bị thu hồi', en: 'Revoked', zh: '已撤销' },
  reason_area_closed: { vi: 'Khu vực đang đóng', en: 'Area Closed', zh: '区域已关闭' },

  // Auth & Permissions
  out_of_hours_reason: { vi: 'Lý do làm việc ngoài giờ (*)', en: 'Out of hours reason (*)', zh: '加班原因 (*)' },
  out_of_hours_required: { vi: 'Vui lòng nhập lý do làm việc ngoài giờ (PCC)!', en: 'Please input out of hours reason (PCC)!', zh: '请输入加班原因（PCC）！' },
  pcc_access_time: { vi: 'Thời gian truy cập PCC (*)', en: 'PCC Access Time (*)', zh: 'PCC 访问时间 (*)' },
  pcc_time_start: { vi: 'Từ giờ', en: 'From', zh: '从' },
  pcc_time_end: { vi: 'Đến giờ', en: 'To', zh: '到' },
  pcc_time_required: { vi: 'Vui lòng chọn đầy đủ thời gian truy cập PCC!', en: 'Please select PCC access time completely!', zh: '请完整选择 PCC 访问时间！' },
  clone_perm: { vi: 'Sao chép cấu hình', en: 'Clone Permissions', zh: '克隆权限' },
  clone_desc: { vi: 'Sao chép toàn bộ cấu hình phân quyền hiện tại sang người dùng khác.', en: 'Copy all current permission settings to other users.', zh: '将所有当前权限设置复制到其他用户。' },
  clone_target_hint: { vi: 'Chọn nhân sự nhận quyền', en: 'Select target personnel', zh: '选择目标人员' },
  clone_success: { vi: 'Sao chép quyền thành công!', en: 'Permissions cloned successfully!', zh: '权限克隆成功！' },
  no_users_selected: { vi: 'Vui lòng chọn ít nhất một nhân sự!', en: 'Please select at least one personnel!', zh: '请选择至少一名人员！' },
  unauthorized_title: { vi: 'Truy cập bị từ chối', en: 'Access Denied', zh: '拒绝访问' },
  unauthorized_desc: { vi: 'Bạn không có quyền quản lý khu vực này. Vui lòng liên hệ Admin.', en: 'You do not have permission to manage this area. Please contact Admin.', zh: '您没有管理此区域的权限。请联系管理员。' },
  unauthorized_device_desc: { vi: 'Bạn không có quyền quản lý thiết bị. Vui lòng liên hệ Admin.', en: 'You do not have permission to manage devices. Please contact Admin.', zh: '您没有管理设备的权限。请联系管理员。' },
  unauthorized_user_desc: { vi: 'Bạn không có quyền quản lý người dùng. Vui lòng liên hệ Admin.', en: 'You do not have permission to manage users. Please contact Admin.', zh: '您没有管理用户的权限。请联系管理员。' },

  // Report Modal
  export_config_desc: { vi: 'Cấu hình các tham số báo cáo trước khi xuất file', en: 'Configure report parameters before exporting', zh: '导出前配置报告参数' },
  export_format: { vi: 'Định dạng xuất', en: 'Export Format', zh: '导出格式' },
  report_summary: { vi: 'Tóm tắt báo cáo', en: 'Report Summary', zh: '报告摘要' },
  export_now: { vi: 'Xuất báo cáo', en: 'Export', zh: '导出' },
  export_csv: { vi: 'Xuất CSV', en: 'Export CSV', zh: '导出 CSV' },
  email_cc_expiry_label: { vi: 'CC Báo Cáo Hết Hạn (08:00)', en: 'Expiry Notice CC (08:00)', zh: '到期提醒抄送 (08:00)' },

  // Area Users Modal
  area_access_list: { vi: 'Danh sách nhân sự được phép', en: 'Authorized Personnel List', zh: '授权人员名单' },
  no_users_found: { vi: 'Chưa có nhân sự nào được cấp quyền truy cập khu vực này.', en: 'No personnel have been granted access to this area yet.', zh: '尚未授权任何人员访问此区域。' },
  col_permission: { vi: 'Quyền hạn', en: 'Permissions', zh: '权限' },
  col_validity: { vi: 'Hiệu lực', en: 'Validity', zh: '有效期' },
  perm_in_out: { vi: 'Vào & Ra', en: 'In & Out', zh: '进 & 出' },
  perm_in_only: { vi: 'Chỉ vào', en: 'In Only', zh: '仅进' },
  perm_out_only: { vi: 'Chỉ ra', en: 'Out Only', zh: '仅出' },

  // Reason Modal
  modal_reason_title: { vi: 'Lý do thay đổi', en: 'Change Reason', zh: '变更原因' },
  modal_grant_reason: { vi: 'Lý do cấp quyền', en: 'Reason for Granting', zh: '授权原因' },
  modal_revoke_reason: { vi: 'Lý do thu hồi quyền', en: 'Reason for Revoking', zh: '撤销原因' },

  // Human-in-the-loop manual audit
  audit_verification: { vi: 'Đối Soát Nhân Sự Thủ Công', en: 'Manual Audit Verification', zh: '人工审核验证' },
  audit_verified_correct: { vi: 'Đã duyệt (Đúng)', en: 'Approved (Correct)', zh: '已审核 (正确)' },
  audit_verified_wrong: { vi: 'Xác nhận SAI', en: 'Intrusion Alert', zh: '确认错误 (入侵)' },
  audit_image_failed: { vi: 'Ảnh nhận diện sai (Hiện tại)', en: 'Incorrect Scan (Current)', zh: '识别错误图像 (当前)' },
  audit_image_success: { vi: 'Ảnh nhận dạng thành công gần nhất', en: 'Nearest Successful Scan', zh: '最近成功识别图像' },
  audit_similarity: { vi: 'Độ tương đồng', en: 'Similarity Rate', zh: '相似度' },
  audit_last_time: { vi: 'Lần cuối lúc:', en: 'Last success:', zh: '最后成功时间:' },
  audit_at_device: { vi: 'Tại thiết bị:', en: 'At Device:', zh: '设备位置:' },
  audit_no_history: { vi: 'Không tìm thấy lịch sử nhận dạng thành công của người này.', en: 'No successful scan history found for this person.', zh: '未找到该人员的成功识别记录。' },
  audit_face8_not_found: { vi: 'Không tìm thấy dữ liệu trên Face 8', en: 'Data not found on Face 8', zh: '在 Face 8 上未找到数据' },
  audit_not_registered: { vi: 'Khuôn mặt chưa từng được đăng ký.', en: 'Face has not been registered yet.', zh: '该面孔尚未注册。' },
  audit_btn_correct: { vi: 'Đúng người (Bỏ qua)', en: 'Correct Person (Allow)', zh: '正确人员 (放行)' },
  audit_btn_wrong: { vi: 'Sai người (Cảnh báo)', en: 'Wrong Person (Alert)', zh: '错误人员 (警报)' },
  audit_loading: { vi: 'Đang tải dữ liệu đối soát...', en: 'Loading verification data...', zh: '正在加载审核 dữ liệu...' },
  audit_done: { vi: 'Đã Đối Soát', en: 'Audited', zh: '已审核' },
  audit_banner_prefix: { vi: 'Người này đã được đối soát: ', en: 'This person has been audited: ', zh: '此人已审核: ' },
  audit_status_correct: { vi: 'ĐÚNG NGƯỜI (Bỏ qua)', en: 'CORRECT PERSON (Allow)', zh: '正确人员 (放行)' },
  audit_status_wrong: { vi: 'SAI NGƯỜI (Cảnh báo)', en: 'WRONG PERSON (Alert)', zh: '错误人员 (警报)' },
  audit_at_time: { vi: ' vào lúc {time}', en: ' at {time}', zh: ' 于 {time}' },

  // Access Requests Specific translations
  access_request: { vi: 'Yêu cầu truy cập', en: 'Access Requests', zh: '访问申请' },
  request_dashboard: { vi: 'Bảng quản lý yêu cầu', en: 'Request Dashboard', zh: '申请控制台' },
  request_subtitle: { vi: 'Quản lý và tạo đơn yêu cầu cấp quyền truy cập khu vực cho nhân sự hoặc nhà thầu', en: 'Manage and create access requests for employees and contractors', zh: '管理和创建员工或承包商的区域访问申请' },
  create_request: { vi: 'Tạo Yêu Cầu Mới', en: 'Create New Request', zh: '创建新申请' },
  request_list: { vi: 'Danh sách đơn yêu cầu', en: 'Request History', zh: '申请历史' },
  request_title: { vi: 'Tiêu đề đơn', en: 'Request Title', zh: '申请标题' },
  request_reason: { vi: 'Lý do / Mục đích', en: 'Reason / Purpose', zh: '申请原因' },
  request_areas: { vi: 'Khu vực yêu cầu', en: 'Requested Areas', zh: '申请区域' },
  request_people: { vi: 'Danh sách người yêu cầu', en: 'Personnel List', zh: '申请人员' },
  request_status: { vi: 'Trạng thái đơn', en: 'Request Status', zh: '申请状态' },
  status_draft: { vi: 'Bản nháp', en: 'Draft', zh: '草稿' },
  status_pending_appr: { vi: 'Chờ phê duyệt', en: 'Pending', zh: '待审批' },
  status_todo_appr: { vi: 'Cần phê duyệt', en: 'To do', zh: '待我审批' },
  status_approved_appr: { vi: 'Đã phê duyệt', en: 'Approved', zh: '已批准' },
  status_rejected_appr: { vi: 'Từ chối', en: 'Rejected', zh: '已拒绝' },
  approver: { vi: 'Người duyệt', en: 'Approver', zh: '审批人' },
  reject_reason: { vi: 'Lý do từ chối', en: 'Reject Reason', zh: '拒绝原因' },
  btn_approve: { vi: 'Phê duyệt', en: 'Approve', zh: '批准' },
  btn_reject: { vi: 'Từ chối', en: 'Reject', zh: '拒绝' },
  others: { vi: 'người khác', en: 'others', zh: '其他人' },
  time_range: { vi: 'Thời hạn truy cập', en: 'Access Duration', zh: '访问期限' },
  start_date: { vi: 'Ngày bắt đầu', en: 'Start Date', zh: '开始日期' },
  end_date: { vi: 'Ngày kết thúc', en: 'End Date', zh: '结束日期' },
  col_person_name: { vi: 'Họ và tên', en: 'Full Name', zh: '姓名' },
  col_identity: { vi: 'CMND / CCCD', en: 'ID / Passport', zh: '身份证号' },
  col_phone: { vi: 'Số điện thoại', en: 'Phone Number', zh: '电话号码' },
  col_company: { vi: 'Đơn vị công tác', en: 'Company / Dept', zh: '工作单位' },
  person_count: { vi: 'Số người', en: 'People count', zh: '人数' },
  import_excel: { vi: 'Nhập từ Excel/CSV', en: 'Import from Excel/CSV', zh: '从Excel导入' },
  add_person: { vi: 'Thêm nhân sự', en: 'Add Person', zh: '添加人员' },
  request_code: { vi: 'Mã đơn', en: 'Request ID', zh: '申请ID' },
  access_time: { vi: 'Thời gian truy cập', en: 'Access Time', zh: '访问时间' },
  authorized_personnel: { vi: 'Nhân sự được cấp quyền', en: 'Authorized Personnel', zh: '被授权人员' },
  requester: { vi: 'Người tạo đơn', en: 'Requester', zh: '申请人' },
  refresh: { vi: 'Làm mới', en: 'Refresh', zh: '刷新' },
  details: { vi: 'Chi tiết', en: 'Details', zh: '详情' },
  submission_time: { vi: 'Thời gian gửi', en: 'Submission Time', zh: '提交时间' },
  valid_time: { vi: 'Thời gian hiệu lực', en: 'Validity Period', zh: '有效时间' },
  purpose_reason: { vi: 'Lý do & mục đích cụ thể', en: 'Specific Reason & Purpose', zh: '具体原因与目的' },
  processing_flow: { vi: 'Quy trình xử lý đơn', en: 'Processing Workflow', zh: '处理流程' },
  reviewing: { vi: 'Xem xét', en: 'Reviewing', zh: '审核中' },
  authorized_personnel_list: { vi: 'Danh sách nhân sự được cấp quyền', en: 'Authorized Personnel List', zh: '授权人员名单' },
  col_emp_id: { vi: 'Mã nhân viên', en: 'Employee ID', zh: '工号' },
  col_department: { vi: 'Đơn vị / Bộ phận', en: 'Department / Unit', zh: '部门 / 单位' },
  review_action_title: { vi: 'Xử lý xét duyệt đơn yêu cầu', en: 'Access Request Review Action', zh: '审核处理申请' },
  btn_approve_grant: { vi: 'Chấp thuận & Cấp quyền', en: 'Approve & Grant Access', zh: '批准并授权' },
  placeholder_reject_reason: { vi: 'Nhập lý do từ chối cụ thể...', en: 'Enter specific rejection reason...', zh: '请输入具体的拒绝原因...' },
  confirm_reject: { vi: 'Xác nhận từ chối', en: 'Confirm Reject', zh: '确认拒绝' },
  remove_row: { vi: 'Xóa dòng', en: 'Remove row', zh: '删除行' },
  add_row: { vi: 'Thêm dòng', en: 'Add row', zh: '添加行' },
  btn_submit_request: { vi: 'Gửi yêu cầu', en: 'Submit', zh: '提交' },
  at_word: { vi: 'lúc', en: 'at', zh: '于' },
  search_request_placeholder: { vi: 'Tìm kiếm theo tiêu đề, lý do...', en: 'Search by title, reason...', zh: '按标题、原因搜索...' },
  cancel_request: { vi: 'Hủy đơn', en: 'Cancel request', zh: '取消申请' },
  no_requests_found: { vi: 'Không có đơn yêu cầu', en: 'No requests found', zh: '未找到申请' },
  no_requests_found_desc: { vi: 'Chưa có đơn yêu cầu truy cập nào khớp với bộ lọc hoặc tìm kiếm.', en: 'No access requests found matching your filters or search.', zh: '未找到符合筛选或搜索条件的访问申请。' },
  start_time_label: { vi: 'Thời điểm bắt đầu', en: 'Start Date & Time', zh: '开始日期与时间' },
  end_time_label: { vi: 'Thời điểm kết thúc (Bỏ trống = Vĩnh viễn)', en: 'End Date & Time (Blank = Permanent)', zh: '结束日期与时间（留空则为永久）' },
  select_areas_label: { vi: 'Chọn khu vực muốn truy cập', en: 'Select areas to access', zh: '选择需要访问的区域' },
  file_processing_error: { vi: 'Lỗi khi xử lý file!', en: 'Error processing file!', zh: '处理文件时出错！' },
  please_select_time_and_area: { vi: 'Vui lòng chọn thời gian bắt đầu và khu vực!', en: 'Please select start time and area!', zh: '请选择开始时间和区域！' },
  please_add_at_least_one_person: { vi: 'Vui lòng thêm ít nhất 1 người vào danh sách yêu cầu!', en: 'Please add at least 1 person to the request list!', zh: '请在申请列表中至少添加 1 人！' },
  request_create_success: { vi: 'Tạo đơn yêu cầu cấp quyền thành công!', en: 'Access request created successfully!', zh: '成功创建访问申请！' },
  request_create_failed: { vi: 'Gặp sự cố khi gửi đơn!', en: 'Problem occurred while submitting the request!', zh: '提交申请时发生问题！' },
  failed_to_load_details: { vi: 'Không thể tải chi tiết đơn!', en: 'Failed to load request details!', zh: '无法加载申请详情！' },
  confirm_cancel_request: { vi: 'Bạn có chắc chắn muốn hủy đơn yêu cầu này không?', en: 'Are you sure you want to cancel this request?', zh: '您确定要取消此申请吗？' },
  request_cancel_success: { vi: 'Đã hủy đơn yêu cầu thành công!', en: 'Request cancelled successfully!', zh: '申请已成功取消！' },
  request_cancel_failed: { vi: 'Không thể hủy đơn này!', en: 'Failed to cancel this request!', zh: '无法取消此申请！' },
  confirm_approve_request: { vi: 'Bạn có chắc chắn muốn phê duyệt đơn này?', en: 'Are you sure you want to approve this request?', zh: '您确定要批准此申请吗？' },
  request_approve_success: { vi: 'Đã duyệt đơn và cấp quyền thành công!', en: 'Request approved and access granted successfully!', zh: '申请已批准，访问权限已成功授予！' },
  request_approve_failed: { vi: 'Gặp lỗi khi xử lý duyệt đơn!', en: 'Error occurred while processing approval!', zh: '处理审批时出错！' },
  please_enter_reject_reason: { vi: 'Vui lòng điền lý do từ chối đơn yêu cầu:', en: 'Please enter the reason for rejecting the request:', zh: '请输入拒绝申请的原因：' },
  request_reject_success: { vi: 'Đã từ chối đơn yêu cầu!', en: 'Request rejected successfully!', zh: '申请已成功拒绝！' },
  registration_desc: { vi: 'Đăng ký danh sách nhân sự vào khu vực kiểm soát', en: 'Register personnel list into controlled areas', zh: '将人员名单注册到受控区域' },
  expected_approval_flow: { vi: 'Lưu trình ký duyệt dự kiến', en: 'Expected Approval Flow', zh: '预计审批流程' },
  flow_loading: { vi: 'Đang tải lưu trình...', en: 'Loading approval flow...', zh: '正在加载审批流程...' },
  no_flow_data: { vi: 'Không có thông tin lưu trình ký duyệt', en: 'No approval flow information', zh: '无审批流程信息' },
  deputy_assigned: { vi: 'Ký thay', en: 'Deputy', zh: '授权给' },
  deputy_reason: { vi: 'Lý do', en: 'Reason', zh: '原因' },
  deputy_mode_always: { vi: 'Luôn hiệu lực', en: 'Always active', zh: '始终有效' },
  waiting: { vi: 'Đang chờ', en: 'Waiting', zh: '等待中' },
  approval_flow: { vi: 'Lưu trình ký duyệt', en: 'Approval Flow', zh: '审批流程' },
  history_level: { vi: 'Cấp duyệt', en: 'Level', zh: '审批级别' },
  history_info: { vi: 'Thông tin người duyệt', en: 'Info', zh: '审批人信息' },
  history_comment: { vi: 'Ghi chú', en: 'Comment', zh: '意见/备注' },
  history: { vi: 'Lịch sử', en: 'History', zh: '历史' },
  // Overtime page translations
  overtime: { vi: 'Tăng ca', en: 'Overtime Exceptions', zh: '加班临时授权' },
  overtime_subtitle: { vi: 'Cấu hình và cấp quyền tăng ca tạm thời theo ngày cho công nhân viên', en: 'Configure and grant day-specific temporary overtime access for employees', zh: '配置和按日授予员工的临时加班访问权限' },
  select_date: { vi: 'Chọn ngày', en: 'Select Date', zh: '选择日期' },
  employee_list: { vi: 'Danh sách nhân viên', en: 'Employee List', zh: '员工列表' },
  search_placeholder_overtime: { vi: 'Tìm tên, mã nv...', en: 'Search name, ID...', zh: '按姓名、工号搜索...' },
  overtime_config: { vi: 'Cấu hình tăng ca', en: 'Overtime Configuration', zh: '加班配置' },
  area: { vi: 'Khu vực', en: 'Area', zh: '区域' },
  select_area: { vi: 'Chọn khu vực...', en: 'Select area...', zh: '选择区域...' },
  save_config: { vi: 'Lưu cài đặt', en: 'Save Configuration', zh: '保存设置' },
  cancel_overtime: { vi: 'Hủy tăng ca', en: 'Cancel Overtime', zh: '取消加班' },
  copy_to_others: { vi: 'Sao chép cho người khác', en: 'Copy to Others', zh: '复制给他人' },
  no_overtime_today: { vi: 'Hôm nay nhân viên này không có lịch tăng ca.', en: 'This employee has no overtime scheduled for today.', zh: '该员工今天没有安排加班。' },
  select_user_to_configure: { vi: 'Vui lòng chọn một nhân viên để thiết lập tăng ca', en: 'Please select an employee to configure overtime', zh: '请选择一名员工以配置加班' },
  established_by: { vi: 'Được thiết lập bởi', en: 'Configured by', zh: '配置人' },
  copy_overtime_hours: { vi: 'Sao chép giờ tăng ca', en: 'Copy Overtime Hours', zh: '复制加班时间' },
  applied_date: { vi: 'Ngày áp dụng', en: 'Applied Date', zh: '应用日期' },
  selected_count_total: { vi: 'Đã chọn: {selected} / {total}', en: 'Selected: {selected} / {total}', zh: '已选：{selected} / {total}' },
  dept_filter: { vi: 'Bộ phận', en: 'Department', zh: '部门' },
  all_depts: { vi: '-- Tất cả bộ phận --', en: '-- All Departments --', zh: '-- 所有部门 --' },
  no_employees_found: { vi: 'Không tìm thấy nhân viên nào', en: 'No employees found', zh: '未找到员工' },
  apply_copy: { vi: 'Áp dụng sao chép', en: 'Apply Copy', zh: '应用复制' },
  please_select_area_and_time: { vi: 'Vui lòng chọn khu vực và giờ kết thúc!', en: 'Please select area and end time!', zh: '请选择区域和结束时间！' },
  save_success: { vi: 'Lưu cấu hình tăng ca thành công!', en: 'Overtime configuration saved successfully!', zh: '加班配置保存成功！' },
  save_failed: { vi: 'Gặp lỗi khi lưu cài đặt!', en: 'Failed to save configuration!', zh: '保存配置失败！' },
  delete_success: { vi: 'Đã hủy lịch tăng ca!', en: 'Overtime configuration deleted!', zh: '加班配置已删除！' },
  delete_failed: { vi: 'Không thể hủy lịch tăng ca!', en: 'Failed to delete overtime configuration!', zh: '无法删除加班配置！' },
  please_select_target_users: { vi: 'Vui lòng chọn ít nhất một nhân viên để sao chép!', en: 'Please select at least one employee to copy to!', zh: '请选择至少一名员工进行复制！' },
  copy_success: { vi: 'Sao chép giờ tăng ca thành công!', en: 'Overtime copied successfully!', zh: '加班复制成功！' },
  copy_failed: { vi: 'Không thể sao chép giờ tăng ca!', en: 'Failed to copy overtime!', zh: '复制加班失败!' },
  optional: { vi: 'Tùy chọn', en: 'Optional', zh: '可选' },
  required: { vi: 'Bắt buộc', en: 'Required', zh: '必填' },
  confirm_delete_overtime: { vi: 'Bạn có chắc chắn muốn hủy lịch tăng ca này?', en: 'Are you sure you want to cancel this overtime schedule?', zh: '您确定要取消此加班安排吗？' },
  confirm_delete_overtime_title: { vi: 'Xác nhận xóa', en: 'Confirm Deletion', zh: '确认删除' },
  delete: { vi: 'Xóa', en: 'Delete', zh: '删除' },
  active_overtime_list: { vi: 'Danh sách nhân viên tăng ca trong ngày', en: 'Active Overtime List for the Day', zh: '当日加班员工名单' },
  no_overtime_records: { vi: 'Không có nhân viên nào đăng ký tăng ca trong ngày này.', en: 'No employees registered for overtime on this date.', zh: '该日期没有登记加班的员工。' },
  col_granted_by: { vi: 'Người cấp', en: 'Granted By', zh: '授权人' },
  notifications: { vi: 'Thông báo', en: 'Notifications', zh: '通知' },
  mark_all_read: { vi: 'Đã xem hết', en: 'Mark all as read', zh: '全部标为已读' },
  no_notifications: { vi: 'Không có thông báo mới', en: 'No new notifications', zh: '没有新通知' }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, data?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('vi');
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
    const savedLang = localStorage.getItem('app-language') as Language;
    if (savedLang && ['vi', 'en', 'zh'].includes(savedLang)) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const safeLanguage = isMounted ? language : 'vi';

  const t = (key: string, data?: Record<string, any>) => {
    let str = TRANSLATIONS[key]?.[safeLanguage] || key;
    if (data) {
      Object.keys(data).forEach(k => {
        const regex = new RegExp(`{${k}}`, 'g');
        str = str.replace(regex, String(data[k]));
      });
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ language: safeLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
